command_timeout = 1000

[aws]
disabled = true

[character]
success_symbol = "[â¯](bold purple)"
vicmd_symbol = "[â®](bold purple)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "â€¦/"
read_only = "î‚¢"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ…³ "

[elixir]
format = '[$symbol$version \(OTP $otp_version\)]($style) '
style = "purple dimmed"
symbol = "ğŸ…´ "

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold black"

[git_commit]
tag_disabled = false

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
conflicted = "â€½"
diverged = "â‡¡${ahead_count}â‡£${behind_count}"
format = '([$all_status$ahead_behind]($style) )'
modified = "Â±"
stashed = "â‡‹"
style = "green"

[hostname]
format = "[$hostname]($style) "
style = "bold purple"

[java]
format = "[${symbol}${version}]($style) "
style = "blue dimmed"
symbol = "ğŸ…¹ "

[nodejs]
format = "[$symbol$version]($style) "
style = "green dimmed"
symbol = "ğŸ…½ "

[package]
format = "[$symbol$version]($style) "
style = "208 dimmed"
symbol = "ğŸ…¿ "

[python]
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
pyenv_prefix = "v"
pyenv_version_name = true
style = "yellow dimmed"
symbol = "ğŸ…¿ "

[ruby]
format = "[$symbol$version]($style) "
style = "red dimmed"
symbol = "ğŸ† "

[rust]
format = "[$symbol$version]($style) "
style = "black"
symbol = "ğŸ† "
